language: python
python:
  - "2.7"
  - "3.11"
  - "3.12"

# command to install dependencies
install: "pip install -r requirements.txt"
script: coverage run --source=pyfpgrowth setup.py test

after_success: coveralls
